### ISSUE TITLE
thenjs.each()函数能够添加遍历类数组的对象功能

### ISSUE THREAD

**Issue by funkyLover** [teambition/then.js#11]
就想jquery的`$.each()`可以用来无缝迭代类数组对象和数组
当然这只是我吹毛求疵的一个需求 = =!

**Comment by zensh** [comment]
`.each` 和 `.eachSeries` 可以历遍类数组啊

**Comment by funkyLover** [comment]
我没去试,readme上写得不够明确.我以为只能是数组
