### ISSUE TITLE
调用完then链以后能否返回一个对象

### ISSUE THREAD

**Issue by zppro** [teambition/then.js#15]
function A(){
  then链读取配置
  return generator 函数
}
这个怎么样控制分支？

**Comment by zensh** [comment]
如果你期望的是同步返回 generator 函数，那么只能把 then 链放到 generator 里面

**Comment by zppro** [comment]
希望将来thenjs能和generator promise整合起来，就像co一样

**Comment by zensh** [comment]
早有了：https://github.com/thunks/thunks ，比 co 还强大
