### ISSUE TITLE
then 链无法被 yield

### ISSUE THREAD

**Issue by zppro** [teambition/then.js#16]
我的设想
function *(){
   yield Thenjs(true).then(function(cont){
      先做的事情
    }
    //后做的事情
}

目前好像做不到

**Comment by zensh** [comment]
目前只有 thunks 支持 yield thenjs链：
```js
thunk = require('thunks');
thenjs = require('thenjs');

thunk(function*() {
  yield thenjs(1).then(/.../);
})();
```

**Comment by zensh** [comment]
`co` 不支持的

**Comment by zppro** [comment]
发现确实不适合做API的场景，特别是流程控制

**Comment by zppro** [comment]
router.post(writePath || 'data/write', koaBody, function *(next) {
            this.type = 'application/json';
            var self = this;

            thunk(function*() {
                yield data.write(self.request.body.k, self.request.body.v, self.request.body.i).then(function(cont){
                    console.log('123');
                    self.body = JSON.stringify({"success": true});
                });
            })();
            console.log('234');
        });

这样做还是不行 thunk(function*(){})();
thunk本身还是异步执行

因此thenjs很难和现有的第三方结合

**Comment by zensh** [comment]
是的，thenjs 不适合用来封装API，thunks 才设计成即可用于封装 API，又可用于控制流。

不过你上面的代码写错了，按照你的思路，应该这样：
```js
router.post(writePath || 'data/write', koaBody, function *(next) {
    this.type = 'application/json';
    var self = this;

    yield thunk(function*() {
        yield data.write(self.request.body.k, self.request.body.v, self.request.body.i).then(function(cont){
            console.log('123');
            self.body = JSON.stringify({"success": true});
        });
    });
    console.log('234');
});
```
但实际上可以更简单，thenjs对象有`toThunk`方法，变成标准 thunk 函数就可以被 `yield`：

```js
router.post(writePath || 'data/write', koaBody, function *(next) {
    this.type = 'application/json';
    var self = this;

    yield data.write(self.request.body.k, self.request.body.v, self.request.body.i).then(function(cont){
        console.log('123');
        self.body = JSON.stringify({"success": true});
    }).toThunk();
    console.log('234');
});
```

如果你已决定用 koa，那么应该用 generator 函数或者 promise 封装 API

**Comment by zppro** [comment]
之前也是按照你上面的逻辑走的
就是少了 cont()
--------------
ok ,解决了
