### ISSUE TITLE
2.0.0更新日志

### ISSUE THREAD

**Issue by AppleGenius** [teambition/then.js#17]
能不能介绍一下2.0.0的更新内容，之前一直使用1.5.0，这种大的版本号更新是不是功能上添加很多feature

**Comment by zensh** [comment]
主要是为了解决这个问题： https://github.com/teambition/then.js/issues/8
另外改变了代码风格，重构了测试代码。

不写更新日志确实不是个好习惯~

**Comment by AppleGenius** [comment]
@zensh 谢谢
