### ISSUE TITLE
thenjs 里面如何获取具体报错的文件和行号？

### ISSUE THREAD

**Issue by no7dw** [teambition/then.js#18]
使用thenjs过程中，看到log：
Thenjs caught error:  [TypeError: Cannot read property 'length' of undefined]
但无具体文件，具体行号。调试找问题会比较不变。
看到是then.js onerror 里面log 出来的：
    
       // 全局 error 监听
      Thenjs.onerror = function (error) {
        console.error('Thenjs caught error: ', error)
        throw error
       }

看起来 error 只是string。
有什么办法知道文件&行号吗？
thanks in advance :-)

**Comment by zensh** [comment]
console.log(error.stack) 能显示出来，chrome 浏览器的话应该能直接看到
