### ISSUE TITLE
希望可以更精确的定位错误信息

### ISSUE THREAD

**Issue by gavinning** [teambition/then.js#21]
thenjs很符合开发者思维，个人感觉用起来比很多promise框架顺手。
但是错误信息定位这个比较麻烦，很难定位到具体错误信息位置，希望这个问题可以有所改进

**Comment by zensh** [comment]
可以实现过滤 thenjs 相关的内部错误堆栈信息

**Comment by zensh** [comment]
但是，这个 `then` 方法与标准不兼容， 标准才是王道，我还是建议使用 promise。
如果你喜欢 callback 风格，可以尝试 https://github.com/thunks/thunks ，这是我目前推荐使用的异步流程控制工具

**Comment by gavinning** [comment]
ok~ 我试试thunks
