### ISSUE TITLE
Thenjs.parallelLimit完全执行结束方案

### ISSUE THREAD

**Issue by dbit-xia** [teambition/then.js#25]
Hi, 大神, 使用过程中发现 Thenjs.parallelLimit //一旦出现错误,就无法知道什么时候完全执行结束,是否可以完善一下?

例如:同时执行一批SQL,其中任何一个出现错误都会进行rollback,这时有可能SQL会在rollback后执行,就有问题了

**Comment by zensh** [comment]
如果有这种依赖关系的，最好还是不要使用 parallel。parallel 是并发，其所有任务都一起运行了，无法退出的。parallelLimit 会保证一旦出错，后续被 limit 的未启动的任务不会启动，但已经启动的任务也是无法退出的。

**Comment by dbit-xia** [comment]
谢谢回复,还是比较喜欢亲的parallelLimit的Limit功能, 只好自己封装了个函数
其实它们相互没有依赖,只是结果一定要等待他们都完成了才能继续

`function parallelLimit(parallel,limit,cb){
    let Thenjs=require('thenjs');
    //let limit=2;
    if (parallel instanceof Array===false) return cb('第一个必须是一个函数数组!');
    let total=parallel.length;
    if (!total) return cb('数组个数至少要有一个元素!');
    let finishCount=0;
    let results=[];
    let errors=[];
    let hasError=false;
    Thenjs.eachLimit(parallel, (cont, fn)=> {
        fn(callback);

        function callback(err,result) {
            if (err) {
                errors.push(err);
            } else {
                results.push(result);
            }
            finishCount++;
            cont(err, result); //如果有错误则开始停止
            if (!hasError && err) {
                hasError = true;
                if (limit && (finishCount + (limit - 1) < total)) {
                    total = finishCount + (limit - 1); //计算最后一个
                }
            }
            if (finishCount >= total) { //全部结束
                cb(errors.length ? errors : null, results);
            }
        }
    }, limit).fail((cont,err)=>{console.error('fail',err)});
}
`
