### ISSUE TITLE
eachLimit 21万个元素的数组,经常到几万的时候就停止了

### ISSUE THREAD

**Issue by dbit-xia** [teambition/then.js#28]
eachLimit 21万个元素的数组,经常到几万的时候就停止了,亲们有遇到过吗?

**Comment by dbit-xia** [comment]
程序运行正常,只是eachLimit的iterator不继续执行了

**Comment by zensh** [comment]
没有试过，JavaScript 的 Array 在长度过万时效率就很低了，过十万不可想象。
真的需要大数组一般用的 https://github.com/thunks/thunk-redis/blob/master/lib/queue.js#L9 这种方案，不过不想在 then.js 中使用它了，因为考虑异步队列不应该这么长~

**Comment by zensh** [comment]
建议监控一下内容占用，是不是逻辑问题导致了频繁 GC 之类

**Comment by dbit-xia** [comment]
我是v6.9.1 demo运行没有问题
我也怀疑是内存占用, 监控内存占用是会一点点的增多,但也都在200M的以内 ,  @zensh 有什么办法可以看出频繁GC (我认为出了作用域就自动GC了)

**Comment by dbit-xia** [comment]
发现一个情况就是这个demo在运行过程中内存占用也会越来越多,是有什么引用导致内存无法及时释放吗?

**Comment by zensh** [comment]
eachLimit 全部完成才会释放数组啊，你说的“运行过程中内存占用也会越来越多”是什么情况

**Comment by Saviio** [comment]
并不是一出scope就立刻/马上GC的，只是被tag成'unneccessary'，然后等STW的时候一起回收掉。

**Comment by nekolab** [comment]
带上`--expose-gc`参数启动node可以暴露`global.gc()`方法，如果怀疑是内存问题可以显式调用这个方法进行排查

**Comment by zensh** [comment]
参考 https://github.com/tj/co/issues/180 监测内存占用

**Comment by dbit-xia** [comment]
用--expose-gc 确实可以释放未引用的变量, 
但是eachLimit完了之后global.gc() 却不能释放,会是什么原因呢? @zensh 
测试代码如下:

var Thenjs = require('thenjs')

function test(cb){
    var list = []
    for (let i = 0; i < 500000; i++) {
        list[i] = new Array(50);
    }
    // return cb(); //直接返回然后global.gc() 可以释放内存
    Thenjs.eachLimit(list, function (cont, value,n) {
        if (n % 1000 === 0) console.log(n);
        cont(null, n)
    }, 100)
    .then(function () {
        cb(); //这里返回然后global.gc() 不能释放内存
    })
}

test(()=>{
    global.gc(); //释放内存
    console.log('结束了,看看内存')
    setTimeout(()=>{},10000)
})

**Comment by zensh** [comment]
释放是被动的

**Comment by dbit-xia** [comment]
谢谢大家,我再继续观察一下
