### ISSUE TITLE
then(cont) 用外层的cont

### ISSUE THREAD

**Issue by dbit-xia** [teambition/then.js#29]
```
const Thenjs=require('thenjs');

Thenjs.each([1,2],(cont,num)=> {
    Thenjs((cont) => {
        cont(null,num);
    }).then(cont)
        .fail((c, err) => {
            cont(err);
        });
}).fin((cont,err,result)=>{
    console.log(err,result);
});
```

//1 undefined  输出正常吗?  为什么不是 null [1,2]

**Comment by zensh** [comment]
写法好怪异

**Comment by zensh** [comment]
输出结果是期望值，主要是因为 `.then(cont).fail` 这里，这里的 then 接收的是 `1`，然后这个 `1` 进入了 cont 的 error 位置，变成了 error，整个 Then 链的结果就是 error: 1

**Comment by Brooooooklyn** [comment]
你这边里层回掉的 `cont ` 被 shadow 了好几次，建议 `cont1` `cont2` 这样区分一下

**Comment by dbit-xia** [comment]
这样写是想 then是直接成功出去,fail要处理一下再返回出去  @zensh 
我试过 fin 没问题的,但是会拦截fail,
所以还是改成了.then((c,result)=>{cont(null,result)});
