### ISSUE TITLE
子Thenjs caught error是否可触发父Thenjs.fail

### ISSUE THREAD

**Issue by dbit-xia** [teambition/then.js#30]
亲,下面这种情况, 输出了:Thenjs caught error:  Error: 3
如果子thenjs未捕获错误,则触发父thenjs的fail是不是更好?使代码看起来还更简洁!

```const Thenjs=require('thenjs');
Thenjs((cont)=>{
    Thenjs((cont)=>{
        cont(Error(3));
    });//.fail(cont);
}).fail((c,err)=>{
    console.error(err);
});
```

**Comment by zensh** [comment]
不注释 `//.fail(cont)` 就是你期望的啊

**Comment by dbit-xia** [comment]
比如有时候会忘记加.fail(cont),然后就会输出thenjs caugth error ,导致外层捕获不到错误了，还不如直接 throw new error

**Comment by zensh** [comment]
你要理解 Node.js 的异步。你的期望不符合程序逻辑。
只可以定义一个全局的 error handler： Thenjs.onerror = function
