### ISSUE TITLE
史上最快有问题

### ISSUE THREAD

**Issue by wujinfeng** [teambition/then.js#34]
史上最快应该是在某个特定版本下，现在nodejs升级很多了，promise性能有了改善。我在v8.11.1测试结果：
**同步**  Sync Benchmark...

JSBench Start, 1000 cycles:
Test Promise...
Test bluebird...
Test co...
Test thunks...
Test thunks-generator...
Test async...
Test thenjs...

JSBench Results:
co: 1000 cycles, 2.901 ms/cycle, 344.709 ops
Promise: 1000 cycles, 2.854 ms/cycle, 350.385 ops
thenjs: 1000 cycles, 1.894 ms/cycle, 527.983 ops
bluebird: 1000 cycles, 1.837 ms/cycle, 544.366 ops
thunks-generator: 1000 cycles, 1.471 ms/cycle, 679.810 ops
thunks: 1000 cycles, 1.316 ms/cycle, 759.878 ops
async: 1000 cycles, 1.006 ms/cycle, 994.036 ops

co: 100%; Promise: 101.65%; thenjs: 153.17%; bluebird: 157.92%; thunks-generator: 197.21%; thunks: 220.44%; async: 288.37%;

JSBench Completed!

**异步** Async Benchmark...

JSBench Start, 1000 cycles:
Test Promise...
Test bluebird...
Test co...
Test thunks...
Test thunks-generator...
Test async...
Test thenjs...
^@
JSBench Results:
bluebird: 1000 cycles, 12.968 ms/cycle, 77.113 ops
Promise: 1000 cycles, 10.511 ms/cycle, 95.138 ops
co: 1000 cycles, 10.16 ms/cycle, 98.425 ops
thunks-generator: 1000 cycles, 7.544 ms/cycle, 132.556 ops
thenjs: 1000 cycles, 7.003 ms/cycle, 142.796 ops
thunks: 1000 cycles, 6.199 ms/cycle, 161.316 ops
async: 1000 cycles, 5.968 ms/cycle, 167.560 ops

bluebird: 100%; Promise: 123.38%; co: 127.64%; thunks-generator: 171.90%; thenjs: 185.18%; thunks: 209.20%; async: 217.29%;

JSBench Completed!

**Comment by zensh** [comment]
嗯，你是对的，有了 async/await 后，其实没必要用这个工具了
