### ISSUE TITLE
series/each 为何不能获得上一个cont的返回值

### ISSUE THREAD

**Issue by goddyZhao** [teambition/then.js#6]
Case：

``` javascript
T(function (cont) {
  cont(null, 1);
}
.series([
  function (cont) {....} // 这里其实想要获得1这个值
  function (cont) {.....}
])
```

现在的workaround就是对于series的操作是同步的就利用全局变量cache住值，异步就得再加一个then，然后用全局变量cache。

最理想的是：

``` javascript
T(function (cont) {
  cont(null, 1);
}
.series([
  function (cont, val, index) {....} // 这样就可以直接访问val了
  function (cont, val, index) {.....}
])
```

另外，作为series，数组中的操作都是串行的，说明意图是操作是有依赖性的，那就应该支持：series中上一个的return值要传递到下一个操作中，否则有得要用全局变量来cache

**Comment by AppleGenius** [comment]
Thenjs(function (cont) {
  cont(null, ['a', 'b', 'c']);
}).
eachSeries(null, function (cont, value, index) {
  console.log(value, index);
  cont();
}).
then(function () {
  console.log('End');
});

这个还是写在文档中吧，无意中发现这个issue，一直都是将each封装在一个function中，传null这种default action还是标明比较好，而且看起来大家的需求还很一致

**Comment by Kevin-Xi** [comment]
LS+1，另外，关于“series中无参数时会读取上一轮结果”这个特性，想知道这是一种trick还是可以稳定依赖的？因为代码中“在上一个then链中异步获得一个数组，在下一个each中处理”这样的逻辑比较多。

**Comment by zensh** [comment]
@Kevin-Xi 这个特性设计之初就存在的，也将会一直存在

**Comment by Kevin-Xi** [comment]
@zensh 好的，谢谢。

**Comment by zensh** [comment]
在另一位道友的 PR 中加上了~ https://github.com/teambition/then.js/pull/33
