### ISSUE TITLE
Thenjs.each()是否可以设置最大"任务并行数量" ?

### ISSUE THREAD

**Issue by tracycool** [teambition/then.js#8]
如async.parallelLimit(tasks, limit, [callback])中的limit

**Comment by no7dw** [comment]
need +1. if so, 如果上层应用控制大概应该怎么做？

**Comment by cool-l** [comment]
设置的这个limit就是max concurrence。假设limit＝5，五个任务并行执行，每完成1个任务，开始执行下一个。即同一时刻，最多有limit个任务并行。 @zensh

**Comment by zensh** [comment]
Ok，我周末尝试解决一下

**Comment by zensh** [comment]
v2.0.0 增加了 `parallelLimit` 和 `eachLimit` 的静态方法和原型方法。
